apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: maahin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-app
spec:
  selector:
    app: mongo-app
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
