apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata: 
  name: wordapp-custom-rules
  namespace: observability
  labels:
    app: kube-prometheus-stack
    release: kube-prom-stack
spec:
  groups:
  - name: wordapp.rules
    rules:
    - alert: host_medium_cpu_load
      expr: (sum(rate(container_cpu_usage_seconds_total{container!=""}[1m])) by (node) * 100) > 50
      for: 0m
      labels:
        severity: warning
        namespace: observability
      annotations:
        description: "Cpu load on host is in warning state \n The value {{ $value }} \n"
        summary: "Cpu load is in warning state \n"
    - alert: host_high_cpu_load
      expr: (sum(rate(container_cpu_usage_seconds_total{container!=""}[1m])) by (node) * 100) > 80
      for: 0m
      labels:
        severity: critical
        namespace: observability
      annotations:
        description: "Cpu load on host is high \n The value {{ $value }} \n"
        summary: "Cpu load is in critical state \n"
    - alert: K8s_pod_crash_looping
      expr: kube_pod_container_status_restarts_total{namespace="default"} > 2
      for: 0m
      labels:
        severity: critical
        namespace: observability
      annotations:
        description: "Pod {{ $labels.pod }} is crash looping \n No. of times={{$value}} \n"
        summary: "Pod is crash looping over 2 times \n"
