apiVersion: v1
kind: Secret
metadata:
  name: secret-webhookurl
  namespace: observability
type: Opaque
data:
  url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA1MDhNNThXUDMvQjA0VVZISkY2RjkvWHVKZHJPVkw3RW1lQ1JOREY0bFNlU2hjCg==
